#index:
#    path: /
#    controller: App\Controller\DefaultController::index
addrapport:
    path: /addrapport
    controller: App\Controller\RapportController::addrapport
    methods: [POST]


login:
    path: /login
    controller: App\Controller\SecurityController::login



default_route:
    path: /creercompte
    controller: App\Controller\UserfController::creercompte
